// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClsrTable: typeof import('./src/components/common/clsrTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColoumn: typeof import('element-plus/es')['ElTableColoumn']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Grid: typeof import('./src/components/common/Grid/index.vue')['default']
    GridItem: typeof import('./src/components/common/Grid/components/GridItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/common/SearchForm/index.vue')['default']
    TableColumn: typeof import('./src/components/common/clsrTable/components/TableColumn.vue')['default']
    UseTable: typeof import('./src/components/clsrTable/useTable.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
